# HOUSE PRICE PREDICTION

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [ ]:
df = pd.read_csv('kc_house_data.csv')
df

id             date  bedrooms  bathrooms  sqft_living  \
0      7129300520  20141013T000000         3       1.00         1180   
1      6414100192  20141209T000000         3       2.25         2570   
2      5631500400  20150225T000000         2       1.00          770   
3      2487200875  20141209T000000         4       3.00         1960   
4      1954400510  20150218T000000         3       2.00         1680   
...           ...              ...       ...        ...          ...   
21608   263000018  20140521T000000         3       2.50         1530   
21609  6600060120  20150223T000000         4       2.50         2310   
21610  1523300141  20140623T000000         2       0.75         1020   
21611   291310100  20150116T000000         3       2.50         1600   
21612  1523300157  20141015T000000         2       0.75         1020   

       sqft_lot  floors  waterfront  view  condition  ...  sqft_above  \
0          5650     1.0           0     0          3  ...        1180   
1          7242     2.0           0     0          3  ...        2170   
2         10000     1.0           0     0          3  ...         770   
3          5000     1.0           0     0          5  ...        1050   
4          8080     1.0           0     0          3  ...        1680   
...         ...     ...         ...   ...        ...  ...         ...   
21608      1131     3.0           0     0          3  ...        1530   
21609      5813     2.0           0     0          3  ...        2310   
21610      1350     2.0           0     0          3  ...        1020   
21611      2388     2.0           0     0          3  ...        1600   
21612      1076     2.0           0     0          3  ...        1020   

       sqft_basement  yr_built  yr_renovated  zipcode      lat     long  \
0                  0      1955             0    98178  47.5112 -122.257   
1                400      1951          1991    98125  47.7210 -122.319   
2                  0      1933             0    98028  47.7379 -122.233   
3                910      1965             0    98136  47.5208 -122.393   
4                  0      1987             0    98074  47.6168 -122.045   
...              ...       ...           ...      ...      ...      ...   
21608              0      2009             0    98103  47.6993 -122.346   
21609              0      2014             0    98146  47.5107 -122.362   
21610              0      2009             0    98144  47.5944 -122.299   
21611              0      2004             0    98027  47.5345 -122.069   
21612              0      2008             0    98144  47.5941 -122.299   

       sqft_living15  sqft_lot15     price  
0               1340        5650  221900.0  
1               1690        7639  538000.0  
2               2720        8062  180000.0  
3               1360        5000  604000.0  
4               1800        7503  510000.0  
...              ...         ...       ...  
21608           1530        1509  360000.0  
21609           1830        7200  400000.0  
21610           1020        2007  402101.0  
21611           1410        1287  400000.0  
21612           1020        1357  325000.0  

[21613 rows x 21 columns]

# **LINEAR REGRESSION**

SIMPLE LINEAR

In [ ]:
df.isnull().sum()

id               0
date             0
bedrooms         0
bathrooms        0
sqft_living      0
sqft_lot         0
floors           0
waterfront       0
view             0
condition        0
grade            0
sqft_above       0
sqft_basement    0
yr_built         0
yr_renovated     0
zipcode          0
lat              0
long             0
sqft_living15    0
sqft_lot15       0
price            0
dtype: int64

In [ ]:
X = df.iloc[:, 4:5]
X

sqft_living
0             1180
1             2570
2              770
3             1960
4             1680
...            ...
21608         1530
21609         2310
21610         1020
21611         1600
21612         1020

[21613 rows x 1 columns]

In [ ]:
Y =df.iloc[:,-1]
Y

0        221900.0
1        538000.0
2        180000.0
3        604000.0
4        510000.0
           ...   
21608    360000.0
21609    400000.0
21610    402101.0
21611    400000.0
21612    325000.0
Name: price, Length: 21613, dtype: float64

In [ ]:
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test = train_test_split(X,Y,test_size=0.2,random_state=0)

In [ ]:
from sklearn.linear_model import LinearRegression
regressor = LinearRegression()
regressor.fit(X_train,Y_train)

LinearRegression()

In [ ]:
#prediction
Y_pred = regressor.predict(X_test)

In [ ]:
#accuracy
from sklearn.metrics import r2_score
print(r2_score(Y_test, Y_pred))

0.4792403526045056


MULTIPLE LINEAR REGRESSION

In [ ]:
X = df.loc[:,['bedrooms','bathrooms','sqft_living', 'waterfront', 'condition','view','lat' ,'sqft_living15','yr_built','grade']]
X

bedrooms  bathrooms  sqft_living  waterfront  condition  view      lat  \
0             3       1.00         1180           0          3     0  47.5112   
1             3       2.25         2570           0          3     0  47.7210   
2             2       1.00          770           0          3     0  47.7379   
3             4       3.00         1960           0          5     0  47.5208   
4             3       2.00         1680           0          3     0  47.6168   
...         ...        ...          ...         ...        ...   ...      ...   
21608         3       2.50         1530           0          3     0  47.6993   
21609         4       2.50         2310           0          3     0  47.5107   
21610         2       0.75         1020           0          3     0  47.5944   
21611         3       2.50         1600           0          3     0  47.5345   
21612         2       0.75         1020           0          3     0  47.5941   

       sqft_living15  yr_built  grade  
0               1340      1955      7  
1               1690      1951      7  
2               2720      1933      6  
3               1360      1965      7  
4               1800      1987      8  
...              ...       ...    ...  
21608           1530      2009      8  
21609           1830      2014      8  
21610           1020      2009      7  
21611           1410      2004      8  
21612           1020      2008      7  

[21613 rows x 10 columns]

In [ ]:
Y = df.iloc[:,-1]
Y

0        221900.0
1        538000.0
2        180000.0
3        604000.0
4        510000.0
           ...   
21608    360000.0
21609    400000.0
21610    402101.0
21611    400000.0
21612    325000.0
Name: price, Length: 21613, dtype: float64

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, random_state=0)

In [ ]:
from sklearn.linear_model import LinearRegression
regressor = LinearRegression()
regressor.fit(X_train, Y_train)

LinearRegression()

In [ ]:
Y_pred = regressor.predict(X_test)

In [ ]:
from sklearn.metrics import r2_score
print(r2_score(Y_test, Y_pred))

0.6880582519711458


# **SUPPORT VECTOR REGRESSION**

In [ ]:
X= df.loc[:,['bedrooms','bathrooms','sqft_living', 'waterfront', 'condition','view','lat' ,'sqft_living15','yr_built','grade']]
Y = df.iloc[:, -1].values

In [ ]:
X

bedrooms  bathrooms  sqft_living  waterfront  condition  view      lat  \
0             3       1.00         1180           0          3     0  47.5112   
1             3       2.25         2570           0          3     0  47.7210   
2             2       1.00          770           0          3     0  47.7379   
3             4       3.00         1960           0          5     0  47.5208   
4             3       2.00         1680           0          3     0  47.6168   
...         ...        ...          ...         ...        ...   ...      ...   
21608         3       2.50         1530           0          3     0  47.6993   
21609         4       2.50         2310           0          3     0  47.5107   
21610         2       0.75         1020           0          3     0  47.5944   
21611         3       2.50         1600           0          3     0  47.5345   
21612         2       0.75         1020           0          3     0  47.5941   

       sqft_living15  yr_built  grade  
0               1340      1955      7  
1               1690      1951      7  
2               2720      1933      6  
3               1360      1965      7  
4               1800      1987      8  
...              ...       ...    ...  
21608           1530      2009      8  
21609           1830      2014      8  
21610           1020      2009      7  
21611           1410      2004      8  
21612           1020      2008      7  

[21613 rows x 10 columns]

In [ ]:
Y

array([221900., 538000., 180000., ..., 402101., 400000., 325000.])

In [ ]:
X.shape

(21613, 10)

In [ ]:
Y.shape

(21613,)

In [ ]:
Y = Y.reshape(len(Y),1)

In [ ]:
#feature scaling
from sklearn.preprocessing import StandardScaler
sc_X = StandardScaler()
sc_Y = StandardScaler()
X= sc_X.fit_transform(X)
Y = sc_Y.fit_transform(Y)

In [ ]:
from sklearn.svm import SVR
regressor = SVR(kernel ='rbf')
regressor.fit(X,Y)

/usr/local/lib/python3.10/dist-packages/sklearn/utils/validation.py:1143: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


SVR()

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, random_state=0)

In [ ]:
Y_pred = regressor.predict(X_test)
Y_pred

array([-0.43354339,  2.93044414, -0.00466756, ..., -0.41737245,
       -0.7896579 , -0.15263535])

In [ ]:
from sklearn.metrics import r2_score
print(r2_score(Y_test, Y_pred))

0.8155985414755744


# **DECISION TREE**

In [ ]:
X = df.loc[:,['bedrooms','bathrooms','sqft_living', 'waterfront', 'condition','view','lat' ,'sqft_living15','yr_built','grade']].values
X

array([[3.000e+00, 1.000e+00, 1.180e+03, ..., 1.340e+03, 1.955e+03,
        7.000e+00],
       [3.000e+00, 2.250e+00, 2.570e+03, ..., 1.690e+03, 1.951e+03,
        7.000e+00],
       [2.000e+00, 1.000e+00, 7.700e+02, ..., 2.720e+03, 1.933e+03,
        6.000e+00],
       ...,
       [2.000e+00, 7.500e-01, 1.020e+03, ..., 1.020e+03, 2.009e+03,
        7.000e+00],
       [3.000e+00, 2.500e+00, 1.600e+03, ..., 1.410e+03, 2.004e+03,
        8.000e+00],
       [2.000e+00, 7.500e-01, 1.020e+03, ..., 1.020e+03, 2.008e+03,
        7.000e+00]])

In [ ]:
Y = df.iloc[:, -1].values
Y

array([221900., 538000., 180000., ..., 402101., 400000., 325000.])

In [ ]:
from sklearn.tree import DecisionTreeRegressor
regressor = DecisionTreeRegressor(random_state = 0)
regressor.fit(X,Y)

DecisionTreeRegressor(random_state=0)

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, random_state=0)

In [ ]:
from sklearn.metrics import r2_score
Y_pred = regressor.predict(X_test)
print(r2_score(Y_test, Y_pred))

0.999258108811741


# **RANDOM FOREST**

In [ ]:
X = df.loc[:,['bedrooms','bathrooms','sqft_living', 'waterfront', 'condition','view','lat' ,'sqft_living15','yr_built','grade']].values
X

array([[3.000e+00, 1.000e+00, 1.180e+03, ..., 1.340e+03, 1.955e+03,
        7.000e+00],
       [3.000e+00, 2.250e+00, 2.570e+03, ..., 1.690e+03, 1.951e+03,
        7.000e+00],
       [2.000e+00, 1.000e+00, 7.700e+02, ..., 2.720e+03, 1.933e+03,
        6.000e+00],
       ...,
       [2.000e+00, 7.500e-01, 1.020e+03, ..., 1.020e+03, 2.009e+03,
        7.000e+00],
       [3.000e+00, 2.500e+00, 1.600e+03, ..., 1.410e+03, 2.004e+03,
        8.000e+00],
       [2.000e+00, 7.500e-01, 1.020e+03, ..., 1.020e+03, 2.008e+03,
        7.000e+00]])

In [ ]:
Y = df.iloc[:, -1].values
Y

array([221900., 538000., 180000., ..., 402101., 400000., 325000.])

In [ ]:
from sklearn.ensemble import RandomForestRegressor
regressor = RandomForestRegressor(n_estimators = 10, random_state = 0)
regressor.fit(X,Y)

RandomForestRegressor(n_estimators=10, random_state=0)

In [ ]:
from sklearn.metrics import r2_score
Y_pred = regressor.predict(X_test)
r2_score(Y, regressor.predict(X))

0.9664052986409917

# **POLYNOMIAL REGRESSION**

In [ ]:
X = df.loc[:,['bedrooms','bathrooms','sqft_living', 'waterfront', 'condition','view','lat' ,'sqft_living15','yr_built','grade']].values
X

array([[3.000e+00, 1.000e+00, 1.180e+03, ..., 1.340e+03, 1.955e+03,
        7.000e+00],
       [3.000e+00, 2.250e+00, 2.570e+03, ..., 1.690e+03, 1.951e+03,
        7.000e+00],
       [2.000e+00, 1.000e+00, 7.700e+02, ..., 2.720e+03, 1.933e+03,
        6.000e+00],
       ...,
       [2.000e+00, 7.500e-01, 1.020e+03, ..., 1.020e+03, 2.009e+03,
        7.000e+00],
       [3.000e+00, 2.500e+00, 1.600e+03, ..., 1.410e+03, 2.004e+03,
        8.000e+00],
       [2.000e+00, 7.500e-01, 1.020e+03, ..., 1.020e+03, 2.008e+03,
        7.000e+00]])

In [ ]:
Y = df.iloc[:, -1].values
Y

array([221900., 538000., 180000., ..., 402101., 400000., 325000.])

In [ ]:
from sklearn.linear_model import LinearRegression
lin_reg = LinearRegression()
lin_reg.fit(X,Y)

LinearRegression()

In [ ]:
from sklearn.preprocessing import PolynomialFeatures
poly_reg = PolynomialFeatures(degree = 2)
X_poly = poly_reg.fit_transform(X)
X

array([[3.000e+00, 1.000e+00, 1.180e+03, ..., 1.340e+03, 1.955e+03,
        7.000e+00],
       [3.000e+00, 2.250e+00, 2.570e+03, ..., 1.690e+03, 1.951e+03,
        7.000e+00],
       [2.000e+00, 1.000e+00, 7.700e+02, ..., 2.720e+03, 1.933e+03,
        6.000e+00],
       ...,
       [2.000e+00, 7.500e-01, 1.020e+03, ..., 1.020e+03, 2.009e+03,
        7.000e+00],
       [3.000e+00, 2.500e+00, 1.600e+03, ..., 1.410e+03, 2.004e+03,
        8.000e+00],
       [2.000e+00, 7.500e-01, 1.020e+03, ..., 1.020e+03, 2.008e+03,
        7.000e+00]])

In [ ]:
X_poly

array([[1.00000000e+00, 3.00000000e+00, 1.00000000e+00, ...,
        9.17668202e+09, 3.28576850e+07, 1.17649000e+05],
       [1.00000000e+00, 3.00000000e+00, 2.25000000e+00, ...,
        9.13916880e+09, 3.27904570e+07, 1.17649000e+05],
       [1.00000000e+00, 2.00000000e+00, 1.00000000e+00, ...,
        4.84248974e+09, 1.50310080e+07, 4.66560000e+04],
       ...,
       [1.00000000e+00, 2.00000000e+00, 7.50000000e-01, ...,
        9.69063048e+09, 3.37652630e+07, 1.17649000e+05],
       [1.00000000e+00, 3.00000000e+00, 2.50000000e+00, ...,
        1.64496015e+10, 6.56670720e+07, 2.62144000e+05],
       [1.00000000e+00, 2.00000000e+00, 7.50000000e-01, ...,
        9.68098566e+09, 3.37484560e+07, 1.17649000e+05]])

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X_poly, Y, test_size = 0.2, random_state = 0)

In [ ]:
lin_reg2 = LinearRegression()
lin_reg2.fit(X_poly, Y)

LinearRegression()

In [ ]:
lin_reg2.fit(X_train, Y_train)

LinearRegression()

In [ ]:
Y_pred = lin_reg2.predict(X_test)

In [ ]:
from sklearn.metrics import r2_score
print(r2_score(Y_test, Y_pred))

0.6111948544633424
